# SQL Interview Questions  - Quiz


## Introduction

This quiz contains questions on topics you can expect to see in an interview pertaining to SQL and Relational Databases. Some of them are multiple choice, while some are short answer. For these short answer questions, double click on the Jupyter Notebook and type your answer below the line. 

## Question 1

What are the 4 main datatypes in SQLite3? Can we use other common types from other kinds of SQL?

Type your answer below this line:
_______________________________________________________________________________________________________________________________
The four main datatypes in SQLite3 are:

INTEGER that is used to store whole numbers both positive and negative.

REAL which stores floating-point numbers .

TEXT which stores text strings.

BLOB which is used to store binary data, such as images or files, exactly as they are input.

Yes, we can use other common SQL data types in SQLite, although SQLite will interpret them according to its internal storage classes.




## Question 2

Explain the relationship between **Primary Keys** and **Foreign Keys**.

Type your answer below this line:
_______________________________________________________________________________________________________________________________
A Primary Key is a unique identifier for each record in a table, which ensures that there are no two rows that have the same value in that particular column.

A Foreign Key is a column in one table that links to the Primary Key in another table,which establishes a relationship between two tables.




## Question 3

Explain the different types of relationships entities can have in a SQL database. 

Type your answer below this line:
_______________________________________________________________________________________________________________________________
One-to-One relationship shows that each record in one table is related to a single record in another table.

One-to-Many relationship shows a single record in one table can be related to multiple records in another table. 

Many-to-One relationship entails multiple records in one table that can relate to a single record in another. This is essentially the reverse of a one-to-many relationship.

Many-to-Many relationship shows records in one table can relate to multiple records in another table and vice versa. 

## Question 4

Explain the various types of JOINs possible with SQL. 

Type your answer below this line:
_______________________________________________________________________________________________________________________________
Inner join returns records with matching values in both tables.
Left join returns all records from the left table and matched records from the right; if no match, NULLs are returned.
Right join returns all records from the right table and matched records from the left; if no match, NULLs are returned.
Full join combines results of both left and right joins, returning all records from both tables with NULLs where there are no matches.


## Question 5

Explain the relationship between Aggregate functions and GROUP BY statements.

Type your answer below this line:
_______________________________________________________________________________________________________________________________
Aggregate functions perform calculations on a set of values to return a single summary value (e.g., SUM, AVG, COUNT), while the GROUP BY statement is used to arrange identical data into groups. However, when used together, GROUP BY organizes the result set into groups based on one or more columns, and aggregate functions calculate values for each group. 

## Question 6

What role do Associative Entities play (JOIN Tables) in many-to-many JOINs?


Type your answer below this line:
_______________________________________________________________________________________________________________________________
Associative entities, or join tables, play a crucial role in many-to-many relationships in SQL databases. They serve as a bridge between two entities by holding foreign keys that reference the primary keys of both entities involved. This structure allows for the creation of associations between multiple records in each table. 


## Summary

In this lesson, we practiced answering open-ended interview questions for SQL and Relational Databases.